image: repo.htl-md.schule:5003/gradle:jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
  KUBERNETES_CPU_REQUEST: "5"
  KUBERNETES_CPU_LIMIT: "10"
  KUBERNETES_MEMORY_REQUEST: "4Gi"
  KUBERNETES_MEMORY_LIMIT: "8Gi"
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "2Gi"
  KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "5Gi"

  KUBERNETES_HELPER_CPU_REQUEST: "5"
  KUBERNETES_HELPER_CPU_LIMIT: "10"
  KUBERNETES_HELPER_MEMORY_REQUEST: "4Gi"
  KUBERNETES_HELPER_MEMORY_LIMIT: "8Gi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_REQUEST: "2Gi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_LIMIT: "5Gi"

  KUBERNETES_SERVICE_CPU_REQUEST: "3"
  KUBERNETES_SERVICE_CPU_LIMIT: "5"
  KUBERNETES_SERVICE_MEMORY_REQUEST: "2Gi"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "4Gi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_REQUEST: "512Mi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_LIMIT: "1Gi"
  CACHE_COMPRESSION_LEVEL: "fastest"

.gradle-cache: &gradle-cache
  key:
    files:
      - plugin/api/build.gradle.kts
      - plugin/bukkit/build.gradle.kts
  paths:
    - "$CI_PROJECT_DIR/.gradle"
  policy: pull

.gradle-project: &gradle-project
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build
    - plugin/api/build
    - plugin/bukkit/build
    - example/kotlin/build
    - example/java/build
  policy: pull-push

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle

# Stages
build:
  stage: build
  script:
    - gradle assemble
  cache:
    - <<: *gradle-cache
      policy: pull-push
    - <<: *gradle-project


test:
  stage: test
  needs: ["build"]
  script:
    - gradle check
  cache:
    - <<: *gradle-cache
    - <<: *gradle-project

deploy:
  stage: deploy
  needs: ["test"]
  script:
    - gradle :solarsystem:plugin:bukkit:shadowJar
  artifacts:
    expire_in: 1 week
    name: "jar-files"
    paths:
      - plugin/bukkit/build/libs/*.jar#
  cache:
    - <<: *gradle-cache
    - <<: *gradle-project
  only:
    - main
    - master
    - test
    - develop
    - tags