name: Server crash or Stacktrace
description: Report server crashes or scary stacktraces
labels: [ "status: needs triage" ]
body:
  - type: textarea
    attributes:
      label: Stack trace
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        If you prefer, you can use a paste site like https://paste.gg.
      value: |
        ```
        paste your stack trace or a paste.gg link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin and Datapack List
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actions to reproduce (if known)
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue. Anything helps!
    validations:
      required: false

  - type: textarea
    attributes:
      label: Plugin version
      description: |
        Run `/about SolarSystem` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/about SolarSystem` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > about SolarSystem
        [01:57:14] [Server thread/INFO]: [SpigotLibraryLoader] [SolarSystem] Loading 1 libraries... please wait
        ...
        [01:57:14] [Server thread/INFO]: [SolarSystem] Loading server plugin SolarSystem v0.0.1
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of Paper from [our downloads page](https://papermc.io/downloads).
        2. Your version of Minecraft is supported by Paper.
        3. Your version of Minecraft is supported by SolarSystem.
        4. You are running the latest version of SolarSystem from [our hangar page](https://hangar.papermc.io/OneLiteFeather/SolarSystem).

        If your server crash log contains `DO NOT REPORT THIS TO PAPER`, please ask in our
        [Discord](https://discord.gg/NZPwRTDWhR) before opening this issue. These messages are informing you of server
        lag and providing debug information.